[package]
name = "plcom"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "plcom"

[[bin]]
name = "plcom"
path = "src/main.rs"

[[bin]]
name = "gen-wallpapers"
path = "src/gen-wallpapers.rs"

[dependencies]
rocket = "0.5"
rocket_async_compression = "0.5"
askama = {  version = "0.12.1", features = ["with-rocket"] }
askama_rocket = "0.12.0"
chrono = "0.4.31"
minify-html = "0.11.1"

# wallpapers
nanorand = { version = "0.7.0", features = ["chacha"] }
kamadak-exif = "0.5.5"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
serde_json = "1.0.108"
dms-coordinates = "1.1.0"